apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-config
data:
  clickhouse-config.xml: |
    <yandex>
      <clickhouse_remote_servers>
        <default_internal>
          <shard_weights>
            <shard>1</shard>
          </shard_weights>
          <replica_weights>
            <replica>1</replica>
          </replica_weights>
          <replica>
            <host>127.0.0.1</host>
            <port>9000</port>
          </replica>
        </default_internal>
        <hot_external>
          <shard_weights>
            <shard>1</shard>
          </shard_weights>
          <replica_weights>
            <replica>1</replica>
          </replica_weights>
          <replica>
            <host>127.0.0.1</host>
            <port>9000</port>
          </replica>
        </hot_external>
        <cold_external>
          <shard_weights>
            <shard>1</shard>
          </shard_weights>
          <replica_weights>
            <replica>1</replica>
          </replica_weights>
          <replica>
            <host>127.0.0.1</host>
            <port>9000</port>
          </replica>
        </cold_external>
      </clickhouse_remote_servers>
      <clickhouse_partitions>
        <move_factor>{{ .Values.clickhouse.moveFactor }}</move_factor>
      </clickhouse_partitions>
    </yandex>
  clickhouse-init.sql: |
    CREATE TABLE dz_test
    (
        `B` Int64,
        `T` String,
        `D` Date
    )
    ENGINE = MergeTree
    PARTITION BY D
    ORDER BY B;

    INSERT INTO dz_test SELECT number, number, '2023-01-01' FROM numbers(1000000000);
