apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
    - protocol: TCP
      port: 9000
      targetPort: 9000
